 const types = {
    REGISTER_REQUEST : 'REGISTER_REQUEST',
    REGISTER_SUCCESS : 'REGISTER_SUCCESS',
    REGISTER_FAILURE : 'REGISTER_FAILURE',
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGOUT : 'LOGOUT',
    RECOVER_PASS_REQUEST : 'RECOVER_PASS_REQUEST',
    RECOVER_PASS_SUCCESS : 'RECOVER_PASS_SUCCESS',
    RECOVER_PASS_FAILURE : 'RECOVER_PASS_FAILURE',
    CHANGE_PASS_REQUEST : 'CHANGE_PASS_REQUEST',
    CHANGE_PASS_SUCCESS : 'CHANGE_PASS_SUCCESS',
    CHANGE_PASS_FAILURE : 'CHANGE_PASS_FAILURE'
  }

  export default types