const types = {
    FETCH_TODOS_SUCCESS : 'FETCH_TODOS_SUCCESS',
    ADD_TODO_SUCCESS : 'ADD_TODO_SUCCESS',
    EDIT_TODO : 'EDIT_TODO',
    DELETE_TODO : 'DELETE_TODO',
    TOGGLE_SWITCH : 'TOGGLE_SWITCH',
    SEARCH_TODOS_SUCCESS : 'SEARCH_TODOS_SUCCESS',
    FILTER_TODO : 'FILTER_TODO'
}
export default types